import { LocaleTable } from './index';

export const zhCN: LocaleTable = {
  // ── extension.ts ──
  'ext.activated': 'GDShader Support 插件已激活.',

  // ── commands.ts ──
  'cmd.shader.spatial': '3D 空间着色器',
  'cmd.shader.canvas_item': '2D 画布着色器',
  'cmd.shader.particles': '粒子着色器',
  'cmd.shader.sky': '天空着色器',
  'cmd.shader.fog': '雾效着色器',
  'cmd.template.placeholder': '选择要插入的着色器模板',
  'cmd.template.vertex': '顶点处理',
  'cmd.template.light': '自定义光照',
  'cmd.template.particleInit': '粒子初始化',
  'cmd.template.particleProcess': '粒子处理',
  'cmd.openGdshaderFile': '请先打开一个 GDShader 文件.',
  'cmd.color.info': '颜色: rgba({0}, {1}, {2}, {3}) | #{4}',
  'cmd.color.notFound': '光标位置未找到颜色值.',

  // ── renameProvider.ts ──
  'rename.builtinNotAllowed': '内置符号不支持重命名.',
  'rename.hintDeclareNotAllowed': '通过 #gdshader-hint-declare 声明的符号不支持重命名.',
  'rename.crossFileNotAllowed': '该符号定义在外部 include 文件中, 不支持跨文件重命名.',

  // ── hoverProvider.ts ──
  'hover.type': '**类型**: `{0}`',
  'hover.keyword': '**关键字**: `{0}`',
  'hover.uniformHint': '**Uniform 提示**: `{0}`',
  'hover.uniformHint.applicableTypes': '适用类型: {0}',
  'hover.builtinVar.notAvailable': '⚠️ *此变量属于 {0}() 上下文, 在当前位置不可用.*',
  'hover.structMember.declaredAt': '*struct {0} 的成员, 声明于第 {1} 行*',
  'hover.declaredAtLine': '*声明于第 {0} 行*',
  'hover.parameter': '参数',
  'hover.parameter.declaredAt': '*参数, 声明于第 {0} 行*',
  'hover.uniform.declaredAt': '*Uniform, 声明于第 {0} 行*',
  'hover.varying.declaredAt': '*Varying, 声明于第 {0} 行*',
  'hover.userFunction.declaredAt': '*用户函数, 声明于第 {0} 行*',
  'hover.constant': '**常量**: `{0}` = {1}',
  'hover.hintDeclare': '*通过 `#gdshader-hint-declare` 声明*',

  // ── completionProvider.ts ──
  'completion.keyword': '关键字',
  'completion.type': '类型',
  'completion.builtinConstant': '内置常量',
  'completion.processorFunction': 'void {0}() - 处理器函数 ({1})',
  'completion.parameter': '参数',
  'completion.hintDeclare.via': '*通过 `#gdshader-hint-declare` 声明*',
  'completion.hintDeclare.detail': '{0} {1} (hint-declare)',
  'completion.type.forHint': '类型 (用于 hint-declare)',
  'completion.preprocessor': '预处理器: {0}',
  'completion.dir.include': '包含文件',
  'completion.dir.define': '宏定义',
  'completion.dir.ifdef': '条件编译 (已定义)',
  'completion.dir.ifndef': '条件编译 (未定义)',
  'completion.dir.if': '条件编译',
  'completion.dir.elif': '条件编译分支',
  'completion.dir.else': '条件编译否则',
  'completion.dir.endif': '条件编译结束',
  'completion.dir.undef': '取消宏定义',
  'completion.folder': '目录',
  'completion.hint.ignore': '忽略此 #include 的诊断提示',
  'completion.hint.declare': '注入符号定义 (变量或函数)',
  'completion.hint.define': '声明一个宏 (等价于 #define, 仅供分析器使用)',
  'completion.hint.type': '为前一个变量指定类型',
  'completion.hint.redirection': '将 include 重定向到相对路径',
  'completion.shaderType': '着色器类型: {0}',
  'completion.renderMode': '渲染模式 ({0})',
  'completion.uniformHint': 'Uniform 提示 ({0})',

  // ── diagnosticsProvider.ts ──
  'diag.redirect.notExist': '重定向目标 "{0}" 不存在. 请检查 #gdshader-hint-redirection 路径.',
  'diag.resPath.unresolved': '无法解析 Godot 资源路径 "{0}". 使用 // #gdshader-hint-redirection:./相对路径 重定向, 或 // #gdshader-hint-ignore 忽略.',
  'diag.include.notFound': '找不到 include 文件 "{0}". 使用 // #gdshader-hint-redirection:./实际路径 重定向, 或 // #gdshader-hint-ignore 忽略.',
  'diag.missingShaderType': '缺少 "shader_type" 声明. GDShader 文件必须以 "shader_type <type>;" 开头.',
  'diag.unknownShaderType': '未知的着色器类型 "{0}". 有效类型: {1}.',
  'diag.processorNotApplicable': '处理器函数 "{0}()" 不适用于 shader_type {1}. 有效处理器: {2}.',
  'diag.discardNotAllowed': '"discard" 不能在 {0}() 中使用, 仅可在 fragment() 和 light() 中使用.',
  'diag.builtinReadonly': '内置变量 "{0}" 在 {1}() 中是只读的 (in), 不能写入.',

  // ── analyzer.ts ──
  'analyzer.builtinConstant': '内置常量: {0} = {1}',
  'analyzer.hintDeclare': '通过 #gdshader-hint-declare 声明',
  'analyzer.duplicateVar': '变量 "{0}" 重复定义.',
  'analyzer.shadowParam': '变量 "{0}" 遮蔽了同名参数.',
  'analyzer.duplicateDecl': '"{0}" 重复定义.',
  'analyzer.structMemberDuplicate': 'struct "{0}" 中成员 "{1}" 重复定义.',
  'analyzer.funcDuplicate': '函数 "{0}" 重复定义.',
  'analyzer.paramDuplicate': '参数 "{0}" 重复定义.',
  'analyzer.undefinedIdent': '未定义的标识符 "{0}".',
  'analyzer.typeMismatch': '类型不匹配: 不能将 "{0}" 赋给 "{1}".',
  'analyzer.argCount': '函数 "{0}" 需要 {1} 个参数, 但传入了 {2} 个.',
  'analyzer.argTypeMismatch': '参数 "{0}" 类型不匹配: 需要 "{1}", 但传入 "{2}".',
  'analyzer.cond.strayElif': '孤立的 #elif: 缺少对应的 #if/#ifdef/#ifndef.',
  'analyzer.cond.strayElse': '孤立的 #else: 缺少对应的 #if/#ifdef/#ifndef.',
  'analyzer.cond.strayEndif': '孤立的 #endif: 缺少对应的 #if/#ifdef/#ifndef.',
  'analyzer.cond.duplicateElse': '同一条件块内出现多个 #else.',
  'analyzer.cond.elifAfterElse': '#elif 不能出现在 #else 之后.',
  'analyzer.cond.unclosed': '{0} 缺少对应的 #endif.',

  // ── parser.ts ──
  'parser.unexpectedToken': "不期望的 token '{0}'.",
  'parser.unexpectedTopLevel': "不期望的顶层 token '{0}'.",
  'parser.expectIdentifier': "期望标识符, 但遇到 '{0}'.",
  'parser.expect': '期望 {0}, 但遇到 \'{1}\'.',
  'parser.missingIfBody': '缺少 if 语句体.',
  'parser.missingForBody': '缺少 for 循环体.',
  'parser.missingWhileBody': '缺少 while 循环体.',
  'parser.missingDoBody': '缺少 do-while 循环体.',
  'parser.switchUnexpected': "switch 中不期望的 token '{0}'.",

  // ── lexer.ts ──
  'lexer.unknownChar': "未知字符 '{0}'.",
  'lexer.unclosedBlockComment': '未闭合的块注释.',
  'lexer.unclosedString': '未闭合的字符串.',

  // ── keywords.ts (常量值) ──
  'const.INF': '无穷大',
  'const.NAN': '非数字',

  // ── 诊断 (processor return) ──
  'diag.returnInProcessor': '处理器函数 {0}() 是 void 返回类型, 不允许使用 return 语句.',
  'diag.returnValueInProcessor': '处理器函数 {0}() 是 void 返回类型, return 不能携带返回值.',

  // ── Hover: shader_type 值 ──
  'hover.shaderTypeValue': '**shader_type**: `{0}`',
  'hover.renderModeValue': '**render_mode**: `{0}`',

  // ── 描述词典 (shader types) ──
  'desc.shaderType.spatial': '3D 空间着色器: 用于渲染 3D 对象 (MeshInstance3D 等), 支持 PBR 光照模型.',
  'desc.shaderType.canvas_item': '2D 画布着色器: 用于渲染 2D 节点 (Sprite2D / TextureRect 等).',
  'desc.shaderType.particles': '粒子着色器: 定义粒子系统的初始化 (start) 与更新 (process) 行为.',
  'desc.shaderType.sky': '天空着色器: 渲染 Sky 资源的背景/反射贴图.',
  'desc.shaderType.fog': '体积雾着色器: 定义 FogVolume 中体素的密度与颜色.',

  // ── 描述词典 (render modes, 精选常用项) ──
  'desc.renderMode.blend_mix': '混合模式: 正常 Alpha 混合 (默认).',
  'desc.renderMode.blend_add': '混合模式: 加法混合.',
  'desc.renderMode.blend_sub': '混合模式: 减法混合.',
  'desc.renderMode.blend_mul': '混合模式: 乘法混合.',
  'desc.renderMode.blend_premul_alpha': '混合模式: 预乘 Alpha.',
  'desc.renderMode.blend_disabled': '禁用混合, 输出直接覆盖目标.',
  'desc.renderMode.depth_draw_opaque': '仅对不透明片元写入深度 (默认).',
  'desc.renderMode.depth_draw_always': '始终写入深度.',
  'desc.renderMode.depth_draw_never': '永不写入深度.',
  'desc.renderMode.depth_prepass_alpha': '使用 Alpha 通道进行深度预通道.',
  'desc.renderMode.depth_test_disabled': '禁用深度测试.',
  'desc.renderMode.depth_test_default': '使用默认的深度测试.',
  'desc.renderMode.depth_test_inverted': '反转深度测试.',
  'desc.renderMode.sss_mode_skin': '次表面散射使用皮肤模式.',
  'desc.renderMode.cull_back': '剔除背面 (默认).',
  'desc.renderMode.cull_front': '剔除正面.',
  'desc.renderMode.cull_disabled': '禁用面剔除, 双面渲染.',
  'desc.renderMode.unshaded': '不参与光照计算, 只输出 ALBEDO.',
  'desc.renderMode.wireframe': '以线框模式渲染.',
  'desc.renderMode.debug_shadow_splits': '调试: 显示阴影级联分段.',
  'desc.renderMode.diffuse_burley': '漫反射模型: Burley (默认).',
  'desc.renderMode.diffuse_lambert': '漫反射模型: Lambert.',
  'desc.renderMode.diffuse_lambert_wrap': '漫反射模型: Lambert Wrap.',
  'desc.renderMode.diffuse_toon': '漫反射模型: 卡通.',
  'desc.renderMode.specular_schlick_ggx': '高光模型: Schlick-GGX (默认).',
  'desc.renderMode.specular_toon': '高光模型: 卡通.',
  'desc.renderMode.specular_disabled': '禁用高光.',
  'desc.renderMode.skip_vertex_transform': '跳过内置的顶点变换, 需自行处理.',
  'desc.renderMode.world_vertex_coords': 'VERTEX 使用世界空间坐标.',
  'desc.renderMode.ensure_correct_normals': '在非均匀缩放下确保法线正确.',
  'desc.renderMode.shadows_disabled': '禁用阴影接收.',
  'desc.renderMode.ambient_light_disabled': '禁用环境光.',
  'desc.renderMode.shadow_to_opacity': '把阴影转换为 Alpha.',
  'desc.renderMode.vertex_lighting': '使用顶点级光照 (性能更好).',
  'desc.renderMode.particle_trails': '启用粒子拖尾.',
  'desc.renderMode.alpha_to_coverage': '启用 Alpha 到覆盖率 (需要 MSAA).',
  'desc.renderMode.alpha_to_coverage_and_one': 'Alpha 到覆盖率, 同时强制 Alpha=1.',
  'desc.renderMode.fog_disabled': '禁用雾.',
  'desc.renderMode.light_only': '仅光照贡献, 不绘制底色.',
  'desc.renderMode.light_vertex_only': '仅顶点光照.',
  'desc.renderMode.unlit': '不参与光照计算.',
  'desc.renderMode.disable_force_vertex_shading': '禁用强制顶点着色.',
  'desc.renderMode.keep_data': '粒子重启时保留数据.',
  'desc.renderMode.disable_force_frame_coherent': '禁用强制帧一致性.',
  'desc.renderMode.collision_use_scale': '粒子碰撞考虑缩放.',
  'desc.renderMode.use_half_res_pass': '启用半分辨率天空通道 (sky).',
  'desc.renderMode.use_quarter_res_pass': '启用四分之一分辨率天空通道 (sky).',
  'desc.renderMode.disable_fog': '禁用雾效混合 (sky).',
  'desc.renderMode.use_debanding': '启用防色带.',

  // ── 描述词典 (uniform hints) ──
  'desc.uniformHint.source_color': '将该 uniform 标记为 sRGB 颜色 (vec3/vec4/sampler2D).',
  'desc.uniformHint.hint_range': '限制数值范围, 生成滑块: hint_range(min, max[, step]).',
  'desc.uniformHint.hint_enum': '显示为下拉枚举: hint_enum("选项A", "选项B", ...).',
  'desc.uniformHint.hint_normal': '将纹理用作法线贴图.',
  'desc.uniformHint.hint_default_white': '缺省值: 不透明白色纹理.',
  'desc.uniformHint.hint_default_black': '缺省值: 不透明黑色纹理.',
  'desc.uniformHint.hint_default_transparent': '缺省值: 透明黑色纹理.',
  'desc.uniformHint.hint_anisotropy': '用作各向异性流图.',
  'desc.uniformHint.hint_roughness': '用于粗糙度限制.',
  'desc.uniformHint.hint_roughness_r': '从 R 通道采样粗糙度.',
  'desc.uniformHint.hint_roughness_g': '从 G 通道采样粗糙度.',
  'desc.uniformHint.hint_roughness_b': '从 B 通道采样粗糙度.',
  'desc.uniformHint.hint_roughness_a': '从 A 通道采样粗糙度.',
  'desc.uniformHint.hint_roughness_normal': '法线贴图引导的粗糙度限制.',
  'desc.uniformHint.hint_roughness_gray': '从灰度采样粗糙度.',
  'desc.uniformHint.hint_screen_texture': '绑定为屏幕纹理 (SCREEN_TEXTURE).',
  'desc.uniformHint.hint_depth_texture': '绑定为深度纹理 (DEPTH_TEXTURE).',
  'desc.uniformHint.hint_normal_roughness_texture': '绑定为法线/粗糙度纹理 (仅 Forward+).',
  'desc.uniformHint.filter_nearest': '采样过滤: 最近邻.',
  'desc.uniformHint.filter_nearest_mipmap': '采样过滤: 最近邻 + mipmap.',
  'desc.uniformHint.filter_nearest_mipmap_anisotropic': '采样过滤: 最近邻 + 各向异性 mipmap.',
  'desc.uniformHint.filter_linear': '采样过滤: 线性.',
  'desc.uniformHint.filter_linear_mipmap': '采样过滤: 线性 + mipmap.',
  'desc.uniformHint.filter_linear_mipmap_anisotropic': '采样过滤: 线性 + 各向异性 mipmap.',
  'desc.uniformHint.repeat_enable': '启用纹理重复.',
  'desc.uniformHint.repeat_disable': '禁用纹理重复 (Clamp).',
  'desc.uniformHint.instance_index': '指定 instance uniform 的索引 (0-15).',

  // ── 描述词典 (类型) ──
  'desc.type.void': '无返回值, 仅用于函数返回类型.',
  'desc.type.bool': '布尔类型, 取值 `true` / `false`.',
  'desc.type.int': '32 位有符号整数.',
  'desc.type.uint': '32 位无符号整数.',
  'desc.type.float': '32 位浮点数 (IEEE 754).',
  'desc.type.vec2': '浮点 2 维向量.',
  'desc.type.vec3': '浮点 3 维向量.',
  'desc.type.vec4': '浮点 4 维向量.',
  'desc.type.bvec2': '布尔 2 维向量.',
  'desc.type.bvec3': '布尔 3 维向量.',
  'desc.type.bvec4': '布尔 4 维向量.',
  'desc.type.ivec2': '有符号整数 2 维向量.',
  'desc.type.ivec3': '有符号整数 3 维向量.',
  'desc.type.ivec4': '有符号整数 4 维向量.',
  'desc.type.uvec2': '无符号整数 2 维向量.',
  'desc.type.uvec3': '无符号整数 3 维向量.',
  'desc.type.uvec4': '无符号整数 4 维向量.',
  'desc.type.mat2': '2x2 浮点矩阵.',
  'desc.type.mat3': '3x3 浮点矩阵.',
  'desc.type.mat4': '4x4 浮点矩阵.',
  'desc.type.sampler2D': '2D 浮点纹理采样器.',
  'desc.type.isampler2D': '2D 有符号整数纹理采样器.',
  'desc.type.usampler2D': '2D 无符号整数纹理采样器.',
  'desc.type.sampler2DArray': '2D 纹理数组采样器.',
  'desc.type.isampler2DArray': '2D 有符号整数纹理数组采样器.',
  'desc.type.usampler2DArray': '2D 无符号整数纹理数组采样器.',
  'desc.type.sampler3D': '3D 体积纹理采样器.',
  'desc.type.isampler3D': '3D 有符号整数纹理采样器.',
  'desc.type.usampler3D': '3D 无符号整数纹理采样器.',
  'desc.type.samplerCube': '立方体纹理采样器.',
  'desc.type.samplerCubeArray': '立方体纹理数组采样器.',
  'desc.type.samplerExternalOES': '外部 OES 纹理采样器 (移动平台).',

  // ── 描述词典 (关键字) ──
  'desc.keyword.shader_type': '声明着色器类型: `shader_type spatial|canvas_item|particles|sky|fog;`, 必须位于文件首部.',
  'desc.keyword.render_mode': '配置渲染模式: `render_mode mode1, mode2, ...;`, 可选值受 shader_type 约束.',
  'desc.keyword.uniform': '声明一个可从外部 (材质/脚本) 设置的 uniform 变量.',
  'desc.keyword.varying': '声明 vertex 与 fragment 之间传递的插值变量.',
  'desc.keyword.const': '声明编译期常量, 必须在定义时初始化.',
  'desc.keyword.struct': '声明结构体类型: `struct Name { members... };`.',
  'desc.keyword.group_uniforms': '将之后声明的 uniform 归入一个 Inspector 分组.',
  'desc.keyword.global': '与 `uniform` 搭配声明全局 uniform: `global uniform ...;`.',
  'desc.keyword.instance': '与 `uniform` 搭配声明每实例 uniform: `instance uniform ...;`.',
  'desc.keyword.flat': 'varying 插值修饰符: 不做插值, 保留提供顶点的值.',
  'desc.keyword.smooth': 'varying 插值修饰符: 透视矫正的平滑插值 (默认).',
  'desc.keyword.in': '形参传递模式: 仅传入 (默认).',
  'desc.keyword.out': '形参传递模式: 仅传出.',
  'desc.keyword.inout': '形参传递模式: 传入并回写.',
  'desc.keyword.lowp': '低精度限定符.',
  'desc.keyword.mediump': '中精度限定符.',
  'desc.keyword.highp': '高精度限定符.',
  'desc.keyword.if': '条件分支: `if (cond) { ... } else { ... }`.',
  'desc.keyword.else': '`if` 的否则分支.',
  'desc.keyword.for': '`for (init; cond; step) { ... }` 计数循环.',
  'desc.keyword.while': '`while (cond) { ... }` 前置条件循环.',
  'desc.keyword.do': '`do { ... } while (cond);` 后置条件循环.',
  'desc.keyword.switch': '多分支跳转: `switch (expr) { case ...: ... default: ... }`.',
  'desc.keyword.case': '`switch` 的分支标签.',
  'desc.keyword.default': '`switch` 的默认分支.',
  'desc.keyword.break': '跳出最近一层循环或 switch.',
  'desc.keyword.continue': '跳到最近一层循环的下一次迭代.',
  'desc.keyword.return': '从函数返回. 注意: 处理器函数 (void) 中不允许使用.',
  'desc.keyword.discard': '丢弃当前片元, 不写入颜色和深度. 仅可在 fragment()/light() 中使用.',
  'desc.keyword.true': '布尔字面量: 真.',
  'desc.keyword.false': '布尔字面量: 假.',
};
