import { LocaleTable } from './index';

export const en: LocaleTable = {
  // ── extension.ts ──
  'ext.activated': 'GDShader Support extension activated.',

  // ── commands.ts ──
  'cmd.shader.spatial': '3D Spatial Shader',
  'cmd.shader.canvas_item': '2D Canvas Item Shader',
  'cmd.shader.particles': 'Particles Shader',
  'cmd.shader.sky': 'Sky Shader',
  'cmd.shader.fog': 'Fog Shader',
  'cmd.template.placeholder': 'Select a shader template to insert',
  'cmd.template.vertex': 'Vertex processing',
  'cmd.template.light': 'Custom lighting',
  'cmd.template.particleInit': 'Particle initialization',
  'cmd.template.particleProcess': 'Particle processing',
  'cmd.openGdshaderFile': 'Please open a GDShader file first.',
  'cmd.color.info': 'Color: rgba({0}, {1}, {2}, {3}) | #{4}',
  'cmd.color.notFound': 'No color value found at cursor position.',

  // ── renameProvider.ts ──
  'rename.builtinNotAllowed': 'Built-in symbols cannot be renamed.',
  'rename.hintDeclareNotAllowed': 'Symbols declared via #gdshader-hint-declare cannot be renamed.',
  'rename.crossFileNotAllowed': 'This symbol is defined in an external include file. Cross-file rename is not supported.',

  // ── hoverProvider.ts ──
  'hover.type': '**Type**: `{0}`',
  'hover.keyword': '**Keyword**: `{0}`',
  'hover.uniformHint': '**Uniform Hint**: `{0}`',
  'hover.uniformHint.applicableTypes': 'Applicable types: {0}',
  'hover.builtinVar.notAvailable': '⚠️ *This variable belongs to {0}() context and is not available here.*',
  'hover.structMember.declaredAt': '*Member of struct {0}, declared at line {1}*',
  'hover.declaredAtLine': '*Declared at line {0}*',
  'hover.parameter': 'parameter',
  'hover.parameter.declaredAt': '*Parameter, declared at line {0}*',
  'hover.uniform.declaredAt': '*Uniform, declared at line {0}*',
  'hover.varying.declaredAt': '*Varying, declared at line {0}*',
  'hover.userFunction.declaredAt': '*User function, declared at line {0}*',
  'hover.constant': '**Constant**: `{0}` = {1}',
  'hover.hintDeclare': '*Declared via `#gdshader-hint-declare`*',

  // ── completionProvider.ts ──
  'completion.keyword': 'Keyword',
  'completion.type': 'Type',
  'completion.builtinConstant': 'Built-in constant',
  'completion.processorFunction': 'void {0}() - Processor function ({1})',
  'completion.parameter': 'parameter',
  'completion.hintDeclare.via': '*Declared via `#gdshader-hint-declare`*',
  'completion.hintDeclare.detail': '{0} {1} (hint-declare)',
  'completion.type.forHint': 'Type (for hint-declare)',
  'completion.preprocessor': 'Preprocessor: {0}',
  'completion.dir.include': 'Include file',
  'completion.dir.define': 'Macro definition',
  'completion.dir.ifdef': 'Conditional (defined)',
  'completion.dir.ifndef': 'Conditional (not defined)',
  'completion.dir.if': 'Conditional',
  'completion.dir.elif': 'Conditional branch',
  'completion.dir.else': 'Conditional else',
  'completion.dir.endif': 'End conditional',
  'completion.dir.undef': 'Undefine macro',
  'completion.folder': 'Folder',
  'completion.hint.ignore': 'Ignore diagnostics for this #include',
  'completion.hint.declare': 'Inject symbol definition (variable or function)',
  'completion.hint.define': 'Declare a macro (equivalent to #define, analyzer-only)',
  'completion.hint.type': 'Specify type for previous variable',
  'completion.hint.redirection': 'Redirect include to relative path',
  'completion.shaderType': 'Shader type: {0}',
  'completion.renderMode': 'Render mode ({0})',
  'completion.uniformHint': 'Uniform hint ({0})',

  // ── diagnosticsProvider.ts ──
  'diag.redirect.notExist': 'Redirection target "{0}" does not exist. Check the #gdshader-hint-redirection path.',
  'diag.resPath.unresolved': 'Cannot resolve Godot resource path "{0}". Use // #gdshader-hint-redirection:./relative_path to redirect, or // #gdshader-hint-ignore to suppress.',
  'diag.include.notFound': 'Include file "{0}" not found. Use // #gdshader-hint-redirection:./actual_path to redirect, or // #gdshader-hint-ignore to suppress.',
  'diag.missingShaderType': 'Missing "shader_type" declaration. GDShader files must start with "shader_type <type>;".',
  'diag.unknownShaderType': 'Unknown shader type "{0}". Valid types: {1}.',
  'diag.processorNotApplicable': 'Processor function "{0}()" is not applicable to shader_type {1}. Valid processors: {2}.',
  'diag.discardNotAllowed': '"discard" cannot be used in {0}(), only in fragment() and light().',
  'diag.builtinReadonly': 'Built-in variable "{0}" is read-only (in) in {1}() and cannot be written to.',

  // ── analyzer.ts ──
  'analyzer.builtinConstant': 'Built-in constant: {0} = {1}',
  'analyzer.hintDeclare': 'Declared via #gdshader-hint-declare',
  'analyzer.duplicateVar': 'Variable "{0}" is already defined.',
  'analyzer.shadowParam': 'Variable "{0}" shadows a parameter with the same name.',
  'analyzer.duplicateDecl': '"{0}" is already defined.',
  'analyzer.structMemberDuplicate': 'Duplicate member "{1}" in struct "{0}".',
  'analyzer.funcDuplicate': 'Function "{0}" is already defined.',
  'analyzer.paramDuplicate': 'Parameter "{0}" is already defined.',
  'analyzer.undefinedIdent': 'Undefined identifier "{0}".',
  'analyzer.typeMismatch': 'Type mismatch: cannot assign "{0}" to "{1}".',
  'analyzer.argCount': 'Function "{0}" expects {1} argument(s), but {2} were provided.',
  'analyzer.argTypeMismatch': 'Argument "{0}" type mismatch: expected "{1}", got "{2}".',
  'analyzer.cond.strayElif': 'Stray #elif: missing matching #if/#ifdef/#ifndef.',
  'analyzer.cond.strayElse': 'Stray #else: missing matching #if/#ifdef/#ifndef.',
  'analyzer.cond.strayEndif': 'Stray #endif: missing matching #if/#ifdef/#ifndef.',
  'analyzer.cond.duplicateElse': 'Duplicate #else in the same conditional block.',
  'analyzer.cond.elifAfterElse': '#elif cannot appear after #else.',
  'analyzer.cond.unclosed': '{0} is missing a matching #endif.',

  // ── parser.ts ──
  'parser.unexpectedToken': "Unexpected token '{0}'.",
  'parser.unexpectedTopLevel': "Unexpected top-level token '{0}'.",
  'parser.expectIdentifier': "Expected identifier, got '{0}'.",
  'parser.expect': "Expected {0}, got '{1}'.",
  'parser.missingIfBody': 'Missing if statement body.',
  'parser.missingForBody': 'Missing for loop body.',
  'parser.missingWhileBody': 'Missing while loop body.',
  'parser.missingDoBody': 'Missing do-while loop body.',
  'parser.switchUnexpected': "Unexpected token '{0}' in switch.",

  // ── lexer.ts ──
  'lexer.unknownChar': "Unknown character '{0}'.",
  'lexer.unclosedBlockComment': 'Unclosed block comment.',
  'lexer.unclosedString': 'Unclosed string.',

  // ── keywords.ts (constant values) ──
  'const.INF': 'Infinity',
  'const.NAN': 'Not a Number',

  // ── diagnostics (processor return) ──
  'diag.returnInProcessor': 'Processor function {0}() returns void; "return" is not allowed inside it.',
  'diag.returnValueInProcessor': 'Processor function {0}() returns void; "return" must not carry a value.',

  // ── Hover: shader_type / render_mode values ──
  'hover.shaderTypeValue': '**shader_type**: `{0}`',
  'hover.renderModeValue': '**render_mode**: `{0}`',

  // ── Descriptions (shader types) ──
  'desc.shaderType.spatial': '3D spatial shader: renders 3D objects (MeshInstance3D, etc.), supports PBR lighting.',
  'desc.shaderType.canvas_item': '2D canvas item shader: renders 2D nodes (Sprite2D, TextureRect, etc.).',
  'desc.shaderType.particles': 'Particles shader: defines the start and process stages of a particle system.',
  'desc.shaderType.sky': 'Sky shader: renders the sky background / reflection map of a Sky resource.',
  'desc.shaderType.fog': 'Volumetric fog shader: defines density and color of voxels in a FogVolume.',

  // ── Descriptions (render modes) ──
  'desc.renderMode.blend_mix': 'Blend mode: normal alpha blending (default).',
  'desc.renderMode.blend_add': 'Blend mode: additive.',
  'desc.renderMode.blend_sub': 'Blend mode: subtractive.',
  'desc.renderMode.blend_mul': 'Blend mode: multiplicative.',
  'desc.renderMode.blend_premul_alpha': 'Blend mode: premultiplied alpha.',
  'desc.renderMode.blend_disabled': 'Disable blending; output overwrites destination.',
  'desc.renderMode.depth_draw_opaque': 'Write depth for opaque fragments only (default).',
  'desc.renderMode.depth_draw_always': 'Always write depth.',
  'desc.renderMode.depth_draw_never': 'Never write depth.',
  'desc.renderMode.depth_prepass_alpha': 'Use alpha channel for depth prepass.',
  'desc.renderMode.depth_test_disabled': 'Disable depth testing.',
  'desc.renderMode.depth_test_default': 'Use the default depth test.',
  'desc.renderMode.depth_test_inverted': 'Invert the depth test.',
  'desc.renderMode.sss_mode_skin': 'Use skin subsurface scattering mode.',
  'desc.renderMode.cull_back': 'Cull back faces (default).',
  'desc.renderMode.cull_front': 'Cull front faces.',
  'desc.renderMode.cull_disabled': 'Disable face culling (double-sided).',
  'desc.renderMode.unshaded': 'Skip lighting; only ALBEDO is output.',
  'desc.renderMode.wireframe': 'Render as wireframe.',
  'desc.renderMode.debug_shadow_splits': 'Debug: visualize shadow cascade splits.',
  'desc.renderMode.diffuse_burley': 'Diffuse model: Burley (default).',
  'desc.renderMode.diffuse_lambert': 'Diffuse model: Lambert.',
  'desc.renderMode.diffuse_lambert_wrap': 'Diffuse model: Lambert wrap.',
  'desc.renderMode.diffuse_toon': 'Diffuse model: toon.',
  'desc.renderMode.specular_schlick_ggx': 'Specular model: Schlick-GGX (default).',
  'desc.renderMode.specular_toon': 'Specular model: toon.',
  'desc.renderMode.specular_disabled': 'Disable specular highlights.',
  'desc.renderMode.skip_vertex_transform': 'Skip the built-in vertex transform; caller handles it.',
  'desc.renderMode.world_vertex_coords': 'VERTEX is expressed in world space.',
  'desc.renderMode.ensure_correct_normals': 'Correct normals under non-uniform scaling.',
  'desc.renderMode.shadows_disabled': 'Disable receiving shadows.',
  'desc.renderMode.ambient_light_disabled': 'Disable ambient light.',
  'desc.renderMode.shadow_to_opacity': 'Convert shadows to alpha.',
  'desc.renderMode.vertex_lighting': 'Use per-vertex lighting (faster).',
  'desc.renderMode.particle_trails': 'Enable particle trails.',
  'desc.renderMode.alpha_to_coverage': 'Enable alpha-to-coverage (requires MSAA).',
  'desc.renderMode.alpha_to_coverage_and_one': 'Alpha-to-coverage, with alpha forced to 1.',
  'desc.renderMode.fog_disabled': 'Disable fog.',
  'desc.renderMode.light_only': 'Draw only the light contribution.',
  'desc.renderMode.light_vertex_only': 'Per-vertex lighting only.',
  'desc.renderMode.unlit': 'Do not participate in lighting.',
  'desc.renderMode.disable_force_vertex_shading': 'Disable forced vertex shading.',
  'desc.renderMode.keep_data': 'Keep particle data on restart.',
  'desc.renderMode.disable_force_frame_coherent': 'Disable forced frame coherence.',
  'desc.renderMode.collision_use_scale': 'Particle collision accounts for scale.',
  'desc.renderMode.use_half_res_pass': 'Enable the half-resolution sky pass.',
  'desc.renderMode.use_quarter_res_pass': 'Enable the quarter-resolution sky pass.',
  'desc.renderMode.disable_fog': 'Disable fog blending (sky).',
  'desc.renderMode.use_debanding': 'Enable debanding.',

  // ── Descriptions (uniform hints) ──
  'desc.uniformHint.source_color': 'Marks the uniform as an sRGB color (vec3/vec4/sampler2D).',
  'desc.uniformHint.hint_range': 'Clamp to a range and show a slider: hint_range(min, max[, step]).',
  'desc.uniformHint.hint_enum': 'Show as a drop-down enum: hint_enum("A", "B", ...).',
  'desc.uniformHint.hint_normal': 'Use the texture as a normal map.',
  'desc.uniformHint.hint_default_white': 'Default to an opaque white texture.',
  'desc.uniformHint.hint_default_black': 'Default to an opaque black texture.',
  'desc.uniformHint.hint_default_transparent': 'Default to a transparent black texture.',
  'desc.uniformHint.hint_anisotropy': 'Use as an anisotropy flowmap.',
  'desc.uniformHint.hint_roughness': 'Used for roughness limiter.',
  'desc.uniformHint.hint_roughness_r': 'Sample roughness from the R channel.',
  'desc.uniformHint.hint_roughness_g': 'Sample roughness from the G channel.',
  'desc.uniformHint.hint_roughness_b': 'Sample roughness from the B channel.',
  'desc.uniformHint.hint_roughness_a': 'Sample roughness from the A channel.',
  'desc.uniformHint.hint_roughness_normal': 'Normal-map-guided roughness limiter.',
  'desc.uniformHint.hint_roughness_gray': 'Sample roughness from the grayscale value.',
  'desc.uniformHint.hint_screen_texture': 'Bind as screen texture (SCREEN_TEXTURE).',
  'desc.uniformHint.hint_depth_texture': 'Bind as depth texture (DEPTH_TEXTURE).',
  'desc.uniformHint.hint_normal_roughness_texture': 'Bind as normal/roughness texture (Forward+ only).',
  'desc.uniformHint.filter_nearest': 'Texture filter: nearest-neighbour.',
  'desc.uniformHint.filter_nearest_mipmap': 'Texture filter: nearest + mipmap.',
  'desc.uniformHint.filter_nearest_mipmap_anisotropic': 'Texture filter: nearest + anisotropic mipmap.',
  'desc.uniformHint.filter_linear': 'Texture filter: linear.',
  'desc.uniformHint.filter_linear_mipmap': 'Texture filter: linear + mipmap.',
  'desc.uniformHint.filter_linear_mipmap_anisotropic': 'Texture filter: linear + anisotropic mipmap.',
  'desc.uniformHint.repeat_enable': 'Enable texture repeat.',
  'desc.uniformHint.repeat_disable': 'Disable texture repeat (clamp).',
  'desc.uniformHint.instance_index': 'Set the instance uniform index (0-15).',

  // ── Descriptions (types) ──
  'desc.type.void': 'No value. Only allowed as a function return type.',
  'desc.type.bool': 'Boolean type; values `true` or `false`.',
  'desc.type.int': '32-bit signed integer.',
  'desc.type.uint': '32-bit unsigned integer.',
  'desc.type.float': '32-bit floating-point number (IEEE 754).',
  'desc.type.vec2': '2-component float vector.',
  'desc.type.vec3': '3-component float vector.',
  'desc.type.vec4': '4-component float vector.',
  'desc.type.bvec2': '2-component boolean vector.',
  'desc.type.bvec3': '3-component boolean vector.',
  'desc.type.bvec4': '4-component boolean vector.',
  'desc.type.ivec2': '2-component signed integer vector.',
  'desc.type.ivec3': '3-component signed integer vector.',
  'desc.type.ivec4': '4-component signed integer vector.',
  'desc.type.uvec2': '2-component unsigned integer vector.',
  'desc.type.uvec3': '3-component unsigned integer vector.',
  'desc.type.uvec4': '4-component unsigned integer vector.',
  'desc.type.mat2': '2x2 float matrix.',
  'desc.type.mat3': '3x3 float matrix.',
  'desc.type.mat4': '4x4 float matrix.',
  'desc.type.sampler2D': '2D float texture sampler.',
  'desc.type.isampler2D': '2D signed-integer texture sampler.',
  'desc.type.usampler2D': '2D unsigned-integer texture sampler.',
  'desc.type.sampler2DArray': '2D texture array sampler.',
  'desc.type.isampler2DArray': '2D signed-integer texture array sampler.',
  'desc.type.usampler2DArray': '2D unsigned-integer texture array sampler.',
  'desc.type.sampler3D': '3D volume texture sampler.',
  'desc.type.isampler3D': '3D signed-integer texture sampler.',
  'desc.type.usampler3D': '3D unsigned-integer texture sampler.',
  'desc.type.samplerCube': 'Cube texture sampler.',
  'desc.type.samplerCubeArray': 'Cube texture array sampler.',
  'desc.type.samplerExternalOES': 'External OES texture sampler (mobile).',

  // ── Descriptions (keywords) ──
  'desc.keyword.shader_type': 'Declares the shader type: `shader_type spatial|canvas_item|particles|sky|fog;`. Must be the first statement.',
  'desc.keyword.render_mode': 'Configures render modes: `render_mode mode1, mode2, ...;`. Allowed modes depend on `shader_type`.',
  'desc.keyword.uniform': 'Declares a uniform variable that can be set from outside (material/script).',
  'desc.keyword.varying': 'Declares a variable interpolated between vertex and fragment stages.',
  'desc.keyword.const': 'Declares a compile-time constant; must be initialized.',
  'desc.keyword.struct': 'Declares a struct type: `struct Name { members... };`.',
  'desc.keyword.group_uniforms': 'Groups subsequent uniforms under an Inspector section.',
  'desc.keyword.global': 'Pairs with `uniform` to declare a global uniform: `global uniform ...;`.',
  'desc.keyword.instance': 'Pairs with `uniform` to declare a per-instance uniform: `instance uniform ...;`.',
  'desc.keyword.flat': 'Varying interpolation qualifier: no interpolation, use the provoking vertex value.',
  'desc.keyword.smooth': 'Varying interpolation qualifier: perspective-correct smooth interpolation (default).',
  'desc.keyword.in': 'Parameter passing mode: input only (default).',
  'desc.keyword.out': 'Parameter passing mode: output only.',
  'desc.keyword.inout': 'Parameter passing mode: input and output.',
  'desc.keyword.lowp': 'Low-precision qualifier.',
  'desc.keyword.mediump': 'Medium-precision qualifier.',
  'desc.keyword.highp': 'High-precision qualifier.',
  'desc.keyword.if': 'Conditional: `if (cond) { ... } else { ... }`.',
  'desc.keyword.else': 'The else branch of an `if` statement.',
  'desc.keyword.for': '`for (init; cond; step) { ... }` loop.',
  'desc.keyword.while': '`while (cond) { ... }` pre-test loop.',
  'desc.keyword.do': '`do { ... } while (cond);` post-test loop.',
  'desc.keyword.switch': 'Multi-way branch: `switch (expr) { case ...: default: ... }`.',
  'desc.keyword.case': 'A branch label of `switch`.',
  'desc.keyword.default': 'The default branch of `switch`.',
  'desc.keyword.break': 'Exit the innermost loop or switch.',
  'desc.keyword.continue': 'Skip to the next iteration of the innermost loop.',
  'desc.keyword.return': 'Return from a function. Note: forbidden inside processor functions (which are void).',
  'desc.keyword.discard': 'Discard the current fragment; only allowed in fragment()/light().',
  'desc.keyword.true': 'Boolean literal: true.',
  'desc.keyword.false': 'Boolean literal: false.',
};
